config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'top#index'
  # root 'groups#index'
  # resources :testsessions, only: :create
  
  resources :task, only: [:new, :create, :edit, :update, :destroy] do
    resources :comment, except: :index do
      put :sort
    end
  end
  resources :groups, only: [ :new, :create, :edit, :update] do
    resources :task, only: [:index, :new, :create, :edit, :update, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  include RankedModel
  ranks :row_order, with_same: :task_id
  
  belongs_to :task

  validates :title, length: { in: 1..255 }
  validates :memo,  length: { in: 1..255 }
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users, dependent: :destroy
  has_many :tasks, dependent: :destroy
  
  validates :name, presence: true, uniqueness: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
  # belongs_to :group
  belongs_to :user
  # belongs_to :groups
  has_many :comments, dependent: :destroy

  # validates :title, length: {in: 1..255}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  #usernameを必須・一意とする
 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users, dependent: :destroy
  has_many :tasks, dependent: :destroy

  validates :username, presence: true, length: { maximum: 20 }
  #usernameを利用してログインするようにオーバーライド
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      #認証の条件式を変更する
      where(conditions).where(["username = :value", { :value => username }]).first
    else
      where(conditions).first
    end
  end

  #emailを不要とする
  def email_required?
    false
  end

  def email_changed?
    false
  end

  def will_save_change_to_email?
    false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end  
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController

  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  def new
    @comment = Comment.new
    @task = Task.find_by(id: params[:task_id])
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.order = Comment.where(task_id: params[:task_id]).maximum(:order).to_i + 1 
    if @comment.save
      redirect_to :root
    else
      render :new
    end
  end

  def show
  end

  def edit
    @tasks = Task.where(user: current_user)
    @comments = Comment.where(task_id: params[:task_id]).rank(:row_order)
  end

  def update
     # タスクに変更があった場合、orderも更新
     if params[:task_id] != comment_params[:task_id]
      @comment.order = Comment.where(task_id: comment_params[:task_id]).maximum(:order).to_i + 1    # Taskにコメントが存在しない場合、nilが返却されるので問題なく動くようにto_iする
    # 並び順に変更があった場合
    elsif @comment.order != comment_params[:order]
      order_after = comment_params[:order].to_i
      # 変更前のorder > 変更後のorder
      if @comment.order > order_after
        (order_after..@comment.order-1).each {|n| 
          @comment_order = Comment.find_by(task_id: params[:task_id], order: n)
          @comment_order.update_attributes(order: n+1)
        }
      # 変更前のorder < 変更後のorder
      elsif @comment.order < order_after
        (@comment.order+1..order_after).each {|n| 
          @comment_order = Comment.find_by(task_id: params[:task_id], order: n)
          @comment_order.update_attributes(order: n-1)
        }
      end
      @comment.order = comment_params[:order]
    end
    if @comment.update_attributes(comment_params)
      redirect_to :root
    else
      render action: :edit
    end
  end


  def destroy
    comments = Comment.where(task_id: params[:task_id], order: @comment.order+1..Float::INFINITY)
    comments.each { |comment|
      comment.update_attributes(order: comment.order-1)
    }
    @comment.destroy
    redirect_to :root
  end


  def sort
    comment = Comment.find(params[:comment_id])
    # after_task_idをtask_idとして渡して処理したい
    comment.update(comment_params)
    render body: nil
  end

  private
    def comment_params
      params.require(:comment).permit(:title, :memo, :task_id, :order, :row_order_position)
    end

    def set_comment
      @comment = Comment.find_by(id: params[:id])
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @group = Group.find_by(id: params[:group_id])
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to group_task_index_path(@group), notice: 'グループを更新しました'
    else
      render :edit
    end
  end


  private
  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end


end

app/controllers/task_controller.rb
class TaskController < ApplicationController

  before_action :set_task, only: [:edit, :update, :destroy]

  def index
    @group = Group.find_by(id: params[:group_id])
  end

  def new
    @group = Group.find_by(id: params[:group_id])
    @task = Task.new
  end

  def create
    if @group = Group.find_by(id: params[:group_id])
      group_create(@group, task_params)
    else
      private_create(task_params)
    end
  end
  
  def group_create(group, param)
    @task = group.tasks.new(param)
    if @task.save
      redirect_to group_task_index_path(group)
    else
      render :new
    end
  end
  def private_create(param)
    @task = Task.new(task_params)
    if @task.save
      redirect_to :root
    else
      render :new
    end
  end

  def edit
    @group = Group.find_by(id: params[:group_id])
  end

  def update
    if @task.update_attributes(task_params)
      redirect_to :root
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to :root
  end



  private
    def task_params
      params.require(:task).permit(:title).merge(user_id: current_user.id)
    end

    def set_task
      @task = Task.find_by(id: params[:id])
    end
end

app/controllers/testsessions_controller.rb
class TestsessionsController < ApplicationController
  
  def create
      user = User.find_by(name:"テスト")
      session[:user_id] = user.id
      flash[:success] = "テストユーザとしてログインしました。"
      redirect_to user
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @tasks = Task.where(user: current_user).order("created_at ASC")
    # @tasks = Task.where(group_url).order("created_at ASC")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    respond_to do |format|
      format.html
      format.json
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/markdown_helper.rb
module MarkdownHelper
  def markdown(text)
    unless @markdown
      options = {
        hard_wrap: true
      }
      extensions = {
        no_intra_emphasis: true,
        tables: true,
        fenced_code_blocks: true,
        autolink: true,
        quote: true
      }
      renderer = Redcarpet::Render::HTML.new(options)
      @markdown = Redcarpet::Markdown.new(renderer, extensions)
    end

    @markdown.render(text).html_safe
  end
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/testsessions_helper.rb
module TestsessionsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comment/edit.html.erb
<div class="commenteditPgae">
  <div class='container'>
    <%= form_with model: @comment, url: { action: :update }, html: { class: 'commenteditForm' }, local: true do |f| %>
      <% if @comment.errors.any? %>
        <p class="text-danger">タイトルは1～255文字以内で入力してください</p>
      <% end %>
      <div class="commenteditForm_title">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control", placeholder: "タイトルを入力してください。  Markdownで記入できます。" %>
      </div>
      <div class="commenteditForm_memo">
        <%= f.label :memo %>
        <%= f.text_area :memo, class: "form-control", placeholder: "詳細を入力してください。  Markdownで記入できます。" %>
      </div>
      <div class="commenteditForm_memo">
        <label>Destination (保管先を変更する場合、選択してください)</label>
        <%= select :comment, :task_id, @tasks.map{ |t| [t.title, t.id] }, {}, { class: 'form-control' } %>
      </div>
      <%= f.hidden_field :order, value: @comment.order %>
      <div class="text-center"><%= f.submit "Update", class: "submitBtn" %></div>
    <% end %>
  </div>
</div>

app/views/comment/new.html.erb
<div class="commentnewPgae">
  <div class='container'>
    <%= form_with model: @comment, url: { action: :create }, html: { class: 'commentnewForm' }, local: true do |f| %>
      <%= f.hidden_field :task_id, value: @task.id %>
      <% if @comment.errors.any? %>
        <p class="text-danger">タイトルは1～255文字以内で入力してください</p>
      <% end %>
      <div class="commentnewForm_title">
        <%= f.label :"Comment Title" %>
        <%= f.text_field :title, autofocus: true, class: "form-control", placeholder: "タイトルを入力してください。  Markdownで記入できます。" %>
      </div>
      <div class="commentnewForm_memo">
        <%= f.label :Memo %>
        <%= f.text_area :memo, autofocus: true, class: "form-control", placeholder: "詳細を入力してください。 Markdownで記入できます。" %>
      <div class="text-center"><%= f.submit "Create ", class: "submitBtn" %></div>
      </div>
    <% end %>
  </div>
</div>

app/views/comment/show.html.erb
<div class='commentdetailPage'>
  <div class="container">
    <div class="commentContents">
      <div class="commentContents_title">
        <div>Comment title</div>
        <span><h2><%= markdown(@comment.title)%></h2></span>
      </div>
      <div class="commentContents_memo">
        <div>Memo</div>
        <span><div><%= markdown(@comment.memo)%></div></span>
      </div>
      <div class="commentContents_taskStatus">
        <div>Storage (現在の保管場所)</div>
        <span><div><%= markdown(@comment.task.title) %></div></span>
      </div>
      <div class="commentContents_btnArea">
        <%= link_to 'Edit', edit_task_comment_path(@comment.task, @comment), class: "edit_btn" %>
        <%= link_to 'Delete', task_comment_path(@comment.task, @comment), class: "text-danger delete_btn", method: :delete, data: { confirm: "このコメントを削除しても宜しいですか?" } %>
      </div>
    </div>
  </div>
</div>

app/views/groups/edit.html.erb
<header class="header2">
  <nav class="nav2">
    <ul class="header_menu2">
      <li class="nav-link">
        <%= @group.name %>
      </li>
      <ul class="header_menu2_inner2">
        <li><%= link_to "Create Group Tasks", new_group_task_path(@group), class: "nav-link listNew2", method: :get %></li>
        <li><%= link_to "Edit Group",edit_group_path(@group), class: "nav-link listNew3", method: :get %></li>
      </ul>
    </ul>
  </nav>
</header>
<div class='groupcreate'> 
  <div class="titleArea">
    <h2>Edit Group</h2>
    <div class="text-center m-3">or</div>
    <%= link_to "Back", :back %>
  </div>

  <div class='container'>
    <%= form_for @group,local: true do |f| %>
      <div class= 'form-input'>Group Name
          <%= f.text_field :name, placeholder: "グループ名を入力してください",class: "form-control" %>
      </div>

      <div class= 'check-box'>Select Member<br>   
          <%= f.collection_check_boxes :user_ids, User.all, :id, :username, class: "check-name" %>
      </div> 

      <div class="actions">
          <%= f.submit "Edit", class: "btn submitBtn" %>
      </div>   
    <% end %>
  </div>  
</div>

app/views/groups/index.html.erb
zzz

<%# .contents
    .contents__member
      .contents__member__current-group
        .group-name
          = @group.name
        .member-name
          member :
          - @group.users.each do |group_user|
            = group_user.name %>

app/views/groups/new.html.erb
<div class='groupcreate'> 
  <div class="titleArea">
  <h2>Create your Group </h2>
  <div class="text-center m-3">or</div>
    <%= link_to "back", :back %>
  </div>

  <div class='container'>
  <%= form_for @group,local: true do |f| %>

  <div class= 'form-input'>Group Name
      <%= f.text_field :name, placeholder: "グループ名を入力してください",class: "form-control" %>
  </div>

  <div class= 'check-box'>Select Member<br>   
      <%= f.collection_check_boxes :user_ids, User.all, :id, :username,class: "check-name" %>
  </div> 

  <div class="actions">
      <%= f.submit "Create", class: "btn submitBtn" %>
  </div>   
  <% end %>

app/views/groups/task.html.erb
aaaa

app/views/groups/task.index.html.erb
aaaa

app/views/task/edit.html.erb
<div class="taskeditPage">
  <div class="container">
    <%= form_with model: @task, url: { action: :update }, html: { class: 'taskForm' }, local: true do |f| %>
      <% if @task.errors.any? %>
        <p class="text-danger">タイトルは1～255文字以内で入力してください</p>
      <% end %>
      <%= f.label :"Task title" %>
      <%= f.text_field :title, class: "form-control taskName", placeholder: "Task Name" %>
      <div class="text-center"><%= f.submit "Update", class: "submitBtn" %></div>
    <% end %>
  </div>
</div>

app/views/task/index.html.erb
<header class="header2">
  <nav class="nav2">
    <ul class="header_menu2">
      <li class="nav-link">
        <%= @group.name %>
      </li>
      <ul class="header_menu2_inner2">
        <li><%= link_to "Create Group Tasks", new_group_task_path(@group), class: "nav-link listNew2" %></li>
        <li><%= link_to "Edit Group",edit_group_path(@group), class: "nav-link listNew3", method: :get %></li>
      </ul>
    </ul>
  </nav>
</header>

<div class="topPage">
  <div class="taskWrapper">
    <% @group.tasks.each do |task| %>
      <div class="task">
        <div class="task_header">
          <h2 class="task_header_title"><span><%= markdown(task.title)%></span></h2>
          <div class="task_header_action">
             <%= link_to content_tag(:i, '', class: 'fas fa-trash'), task, method: :delete, data: { confirm: "#{task.title}を本当に削除しますか？" } %>
            <%= link_to(content_tag(:i, '', class: 'fas fa-pen'), edit_task_path(task)) %>
          </div>
        </div>
        <div class="commentWrapper">
           <div class="commentTask">
            <% task.comments.rank(:row_order).each do |comment| %>
              <%= content_tag "div", id: "comment-#{comment.id}", data: { model_name: comment.class.name.underscore, update_url: task_comment_sort_path(comment.task, comment)} do %>
                <div class="comment">
                  <%= link_to task_comment_path(task, comment), class:"commentDetail_link" do %>
                    <div class="comment_title"><span><%= markdown(comment.title)%></span></div>
                    <% if comment.memo.size > 0 %>
                      <div class="comment_detail is-exist"><i class="fas fa-bars"></i></div>
                    <% end %>
                  <% end %>
                </div>
              <% end %>
            <% end %>  
          </div>
          <div class="addComment">
            <i class="far fa-plus-square"></i>
            <%= link_to "Add Comments", new_task_comment_path(task), class: "addComment_link" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/task/new.html.erb
<% - if @group.present?%>
  <header class="header2">
    <nav class="nav2">
      <ul class="header_menu2">
          <li class="nav-link">
              <%= @group.name %>
          </li>
          <ul class="header_menu2_inner2">
            <li><%= link_to "Create Group Tasks", new_group_task_path(@group), class: "nav-link listNew2", method: :get %></li>
            <li><%= link_to "Edit Group",edit_group_path(@group), class: "nav-link listNew3", method: :get %></li>
          </ul>
        </ul>
    </nav>
  </header>
  <div class="tasknewPage">
    <div class="container">
      <%= form_with model: @task, url: { action: :create }, class: "new_task", local: true do |f| %>
        <%= f.label :"Group task title" %>
        <%= f.text_field :title, autofocus: true, class: "form-control taskName", placeholder: "タスク名を入力してください。  Markdownで記入できます。" %>
        <div class="text-center"><%= f.submit "Create", class: "submitBtn" %></div>
      <% end %>

<%  else %>
  <div class="tasknewPage2">
    <div class="container">
  <%= form_with model: @task, url: { action: :create }, class: "new_task2", local: true do |f| %>
    <%= f.label :"Your Task Title" %>
    <%= f.text_field :title, autofocus: true, class: "form-control taskName", placeholder: "タスク名を入力してください。  Markdownで記入できます。" %>
    <div class="text-center"><%= f.submit "Create", class: "submitBtn" %></div>
  <% end %>
<% end %>

app/views/top/index.html.erb
<div class="topPage">
  <div class="taskWrapper">
    <% @tasks.each do |task| %>
      <div class="task">
        <div class="task_header">
          <h2 class="task_header_title"><span><%= markdown(task.title)%></span></h2>
          <div class="task_header_action">
             <%= link_to content_tag(:i, '', class: 'fas fa-trash'), task, method: :delete, data: { confirm: "#{task.title}を本当に削除しますか？" } %>
            <%= link_to(content_tag(:i, '', class: 'fas fa-pen'), edit_task_path(task)) %>
          </div>
        </div>
        <div class="commentWrapper">
          <div class="commentTask">
            <% task.comments.rank(:row_order).each do |comment| %>
              <%= content_tag "div", id: "comment-#{comment.id}", data: { model_name: comment.class.name.underscore, update_url: task_comment_sort_path(comment.task, comment)} do %>
                <div class="comment">
                  <%= link_to task_comment_path(task, comment), class:"commentDetail_link" do %>
                    <div class="comment_title"><span><%= markdown(comment.title)%></span></div>
                    <% if comment.memo.size > 0 %>
                      <div class="comment_detail is-exist"><i class="fas fa-bars"></i></div>
                    <% end %>
                  <% end %>
                </div>
              <% end %>
            <% end %>  
          </div>    
          <div class="addComment">
            <i class="far fa-plus-square"></i>
            <%= link_to "Add Comments", new_task_comment_path(task), class: "addComment_link" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>