config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'top#index'
  # root 'groups#index'
  # resources :testsessions, only: :create
  
  resources :task, only: [:new, :create, :edit, :update, :destroy] do
    resources :comment, except: :index do
      put :sort
    end
  end
  resources :groups, only: [ :new, :create, :edit, :update] do
    resources :task, only: [:index, :new, :create, :edit, :update, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  include RankedModel
  ranks :row_order, with_same: :task_id
  
  belongs_to :task

  validates :title, length: { in: 1..255 }
  validates :memo,  length: { in: 1..255 }
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users, dependent: :destroy
  has_many :tasks, dependent: :destroy
  
  validates :name, presence: true, uniqueness: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
  # belongs_to :group
  belongs_to :user
  # belongs_to :groups
  has_many :comments, dependent: :destroy

  # validates :title, length: {in: 1..255}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  #usernameを必須・一意とする
 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users, dependent: :destroy
  has_many :tasks, dependent: :destroy

  validates :username, presence: true, length: { maximum: 20 }
  #usernameを利用してログインするようにオーバーライド
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      #認証の条件式を変更する
      where(conditions).where(["username = :value", { :value => username }]).first
    else
      where(conditions).first
    end
  end

  #emailを不要とする
  def email_required?
    false
  end

  def email_changed?
    false
  end

  def will_save_change_to_email?
    false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end  
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController

  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  def new
    @comment = Comment.new
    @task = Task.find_by(id: params[:task_id])
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.order = Comment.where(task_id: params[:task_id]).maximum(:order).to_i + 1 
    if @comment.save
      redirect_to :root
    else
      render :new
    end
  end

  def show
  end

  def edit
    @tasks = Task.where(user: current_user)
    @comments = Comment.where(task_id: params[:task_id]).rank(:row_order)
  end

  def update
     # タスクに変更があった場合、orderも更新
     if params[:task_id] != comment_params[:task_id]
      @comment.order = Comment.where(task_id: comment_params[:task_id]).maximum(:order).to_i + 1    # Taskにコメントが存在しない場合、nilが返却されるので問題なく動くようにto_iする
    # 並び順に変更があった場合
    elsif @comment.order != comment_params[:order]
      order_after = comment_params[:order].to_i
      # 変更前のorder > 変更後のorder
      if @comment.order > order_after
        (order_after..@comment.order-1).each {|n| 
          @comment_order = Comment.find_by(task_id: params[:task_id], order: n)
          @comment_order.update_attributes(order: n+1)
        }
      # 変更前のorder < 変更後のorder
      elsif @comment.order < order_after
        (@comment.order+1..order_after).each {|n| 
          @comment_order = Comment.find_by(task_id: params[:task_id], order: n)
          @comment_order.update_attributes(order: n-1)
        }
      end
      @comment.order = comment_params[:order]
    end
    if @comment.update_attributes(comment_params)
      redirect_to :root
    else
      render action: :edit
    end
  end


  def destroy
    comments = Comment.where(task_id: params[:task_id], order: @comment.order+1..Float::INFINITY)
    comments.each { |comment|
      comment.update_attributes(order: comment.order-1)
    }
    @comment.destroy
    redirect_to :root
  end


  def sort
    comment = Comment.find(params[:comment_id])
    # after_task_idをtask_idとして渡して処理したい
    comment.update(comment_params)
    render body: nil
  end

  private
    def comment_params
      params.require(:comment).permit(:title, :memo, :task_id, :order, :row_order_position)
    end

    def set_comment
      @comment = Comment.find_by(id: params[:id])
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @group = Group.find_by(id: params[:group_id])
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to group_task_index_path(@group), notice: 'グループを更新しました'
    else
      render :edit
    end
  end


  private
  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end


end

app/controllers/task_controller.rb
class TaskController < ApplicationController

  before_action :set_task, only: [:edit, :update, :destroy]

  def index
    @group = Group.find_by(id: params[:group_id])
  end

  def new
    @group = Group.find_by(id: params[:group_id])
    @task = Task.new
  end

  def create
    if @group = Group.find_by(id: params[:group_id])
      group_create(@group, task_params)
    else
      private_create(task_params)
    end
  end
  
  def group_create(group, param)
    @task = group.tasks.new(param)
    if @task.save
      redirect_to group_task_index_path(group)
    else
      render :new
    end
  end
  def private_create(param)
    @task = Task.new(task_params)
    if @task.save
      redirect_to :root
    else
      render :new
    end
  end

  def edit
    @group = Group.find_by(id: params[:group_id])
  end

  def update
    if @task.update_attributes(task_params)
      redirect_to :root
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to :root
  end



  private
    def task_params
      params.require(:task).permit(:title).merge(user_id: current_user.id)
    end

    def set_task
      @task = Task.find_by(id: params[:id])
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @tasks = Task.where(user: current_user).order("created_at ASC")
    # @tasks = Task.where(group_url).order("created_at ASC")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    respond_to do |format|
      format.html
      format.json
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/markdown_helper.rb
module MarkdownHelper
  def markdown(text)
    unless @markdown
      options = {
        hard_wrap: true
      }
      extensions = {
        no_intra_emphasis: true,
        tables: true,
        fenced_code_blocks: true,
        autolink: true,
        quote: true
      }
      renderer = Redcarpet::Render::HTML.new(options)
      @markdown = Redcarpet::Markdown.new(renderer, extensions)
    end

    @markdown.render(text).html_safe
  end
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/testsessions_helper.rb
module TestsessionsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Good2me</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>   
    <%= render 'partial/header' if current_user %>
    <%# <%= render 'partial/header2' if @group %>
    <% if flash[:notice] %>
      <div class="alert alert-info">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/partial/_header.html.erb
<header class="header">
  <nav class="nav">
    <ul class="header_menu">
      <li class="nav-link"><%= current_user.username %>さん</li>
       <li class="header_menu_groups">
       <%= link_to "Create Group", new_group_path,class: "listNew4",method: :get %><a class="header_menu_currents">
       Your Groups：
       <% current_user.groups.each do |group|%>
       <%= link_to group_task_index_path(group),class: "header_menu_currents_name",method: :get do %>
       <%= group.name%>
       <% end %></a><% end %></li>
       
      <li class="header_menu_title"><%= link_to "TasK I N G", root_path, class: "nav-link" %></li>
      <li>
        <ul class="header_menu_inner">
          <li><%= link_to "Create Task", new_task_path, class: "nav-link listNew1" %></li>
          <li><%= link_to "Edit", edit_user_registration_path, class: "nav-link listNew2", method: :get %></li>
          <li><%= link_to "Sign out", destroy_user_session_path, class: "nav-link listNew3", method: :delete %></li>

        </ul>
      </li>
    </ul>
  </nav>
</header>

app/views/partial/_header2.html.erb
<%# <header class="header2">
  <nav class="nav2">
    <ul class="header_menu2">
      <li class="nav-link">
        <%= @group.name %>
      <%# </li>
      <ul class="header_menu2_inner2">
        <li><%= link_to "Create Group Tasks", new_group_task_path(@group), class: "nav-link listNew2", method: :get %>
        <%# </li>
        <li><%= link_to "Edit Group",edit_group_path(@group), class: "nav-link", method: :get %>